# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    - name: Swift Package Manager
      run: xcodebuild -resolvePackageDependencies -scheme MyGames -project ./MyGames.xcodeproj
    - name: Run build
      run: xcodebuild build -scheme MyGames -project ./MyGames.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8'
